namespace Brainy.Domain.Entities;

/// <summary>
/// Base type for all persisted entities. Provides a surrogate key, audit timestamps,
/// and an optimistic concurrency token.
/// </summary>
public abstract class BaseEntity
{
    public Guid Id { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    /// <summary>
    /// Optimistic concurrency token (SQL Server <c>rowversion</c>), regenerated by the
    /// store on every write. Saving with a stale value throws instead of silently
    /// overwriting changes made by another tab or circuit. Null until first persisted.
    /// </summary>
    public byte[]? RowVersion { get; set; }
}
