using Brainy.Domain.Common;
using Brainy.Domain.Enums;

namespace Brainy.Domain.Entities;

/// <summary>
/// A deliverable created by reusing stored knowledge (CODE: Express). May be drafted
/// by the user or generated by AI from a set of source notes.
/// </summary>
public class Output : BaseEntity, IUserOwnedEntity
{
    /// <summary>Identity key of the owning user.</summary>
    public string UserId { get; set; } = string.Empty;

    public string Title { get; set; } = string.Empty;

    public string? Description { get; set; }

    public string Content { get; set; } = string.Empty;

    public OutputType Type { get; set; }

    public OutputStatus Status { get; set; }

    /// <summary>True when produced by an AI provider rather than the user.</summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>The AI model used, when applicable (provenance).</summary>
    public string? Model { get; set; }

    /// <summary>The versioned prompt used to generate the output (provenance).</summary>
    public string? PromptVersion { get; set; }

    public Guid? ProjectId { get; set; }

    public Project? Project { get; set; }

    public Guid? AreaId { get; set; }

    public Area? Area { get; set; }

    public Guid? GoalId { get; set; }

    public Goal? Goal { get; set; }

    public DateTime? PublishedDate { get; set; }

    public DateTime? ArchivedDate { get; set; }

    public string? ArchivedReason { get; set; }

    public bool IsArchived { get; set; }

    /// <summary>The notes this output was distilled from.</summary>
    public ICollection<Note> SourceNotes { get; set; } = new List<Note>();
}
