namespace Brainy.Domain.Entities;

/// <summary>
/// A distilled summary of a note. May be authored by the user or generated by AI;
/// provenance is always tracked so AI output can be identified and audited.
/// </summary>
public class Summary : BaseEntity
{
    public Guid NoteId { get; set; }

    public Note Note { get; set; } = null!;

    public string Content { get; set; } = string.Empty;

    /// <summary>True when produced by an AI provider rather than the user.</summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>The AI model used, when applicable (provenance).</summary>
    public string? Model { get; set; }

    /// <summary>The versioned prompt used to generate the summary (provenance).</summary>
    public string? PromptVersion { get; set; }
}
